version: '3.1'

services:
    api-express:
        build:
            context: ./api
        container_name: node-express
        depends_on:
            - mongo
        restart: always
        ports:
            - "53000:53000"
        volumes:
            - ./api:/api
        networks:
            - api-rest
        command: npm run start

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
        volumes:
            - ./api/db:/data/db
        networks:
            - api-rest

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
            ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
            ME_CONFIG_MONGODB_URL: $MONGO_URL
        networks:
            - api-rest

networks:
    api-rest:
        driver: bridge
