version: '3.1'

services:
    api-express:
        build:
            context: ./api
        container_name: node-express
        depends_on:
            - mongo
        restart: always
        ports:
            - "53000:53000"
        volumes:
            - ./api:/api
        networks:
            - api-rest
        command: node server.js

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - ./api/db:/data/db
        networks:
            - api-rest

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
        networks:
            - api-rest

networks:
    api-rest:
        driver: bridge
